// <auto-generated />
namespace IdeareOrcamentos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _190921_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_190921_1));
        
        string IMigrationMetadata.Id
        {
            get { return "202109192018125_190921_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
